# Generated by Django 3.0 on 2020-03-18 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hakbu', models.CharField(max_length=200)),
                ('Hakgwa', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentID', models.IntegerField()),
                ('year', models.IntegerField(null=True)),
                ('Hakbu', models.CharField(max_length=200)),
                ('Hakgwa', models.CharField(max_length=200)),
                ('WantCredit1', models.IntegerField(default=0)),
                ('WantCredit2', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campus', models.CharField(max_length=20)),
                ('courseID', models.CharField(max_length=20)),
                ('courseName', models.CharField(max_length=200)),
                ('Credit1', models.CharField(max_length=20)),
                ('Credit2', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('class_day', models.CharField(max_length=200)),
                ('class_type', models.CharField(max_length=20)),
                ('profName', models.CharField(max_length=200)),
                ('credit_time', models.CharField(max_length=10)),
                ('etc', models.CharField(max_length=200, null=True)),
                ('prof_rating', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('class_rating', models.DecimalField(decimal_places=2, max_digits=1000, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hakbu_School', to='course.School')),
            ],
        ),
    ]
