# Generated by Django 3.0 on 2020-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='Hakgwa',
            field=models.CharField(max_length=200),
        ),
    ]
