# Generated by Django 3.0.5 on 2020-04-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200318_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
